// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthControllerGetMeData, AuthControllerGetMeResponses, AuthControllerLoginData, AuthControllerLoginResponses, AuthControllerLogoutData, AuthControllerLogoutResponses, AuthControllerRefreshData, AuthControllerRefreshResponses, AuthControllerRegisterData, AuthControllerRegisterResponses, UsersControllerCreateUserData, UsersControllerCreateUserResponses, UsersControllerGetAllUsersData, UsersControllerGetAllUsersResponses, UsersControllerGetUserByIdData, UsersControllerGetUserByIdResponses, UsersControllerRemoveUserData, UsersControllerRemoveUserResponses, UsersControllerUpdateUserData, UsersControllerUpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const authControllerGetMe = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerGetMeData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerGetMeResponses, unknown, ThrowOnError>({ url: '/api/auth/me', ...options });

export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>) => (options.client ?? client).post<AuthControllerRegisterResponses, unknown, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerLogin = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>) => (options.client ?? client).post<AuthControllerLoginResponses, unknown, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerLogoutResponses, unknown, ThrowOnError>({ url: '/api/auth/logout', ...options });

export const authControllerRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerRefreshResponses, unknown, ThrowOnError>({ url: '/api/auth/refresh', ...options });

export const usersControllerGetAllUsers = <ThrowOnError extends boolean = false>(options?: Options<UsersControllerGetAllUsersData, ThrowOnError>) => (options?.client ?? client).get<UsersControllerGetAllUsersResponses, unknown, ThrowOnError>({ url: '/api/users', ...options });

export const usersControllerCreateUser = <ThrowOnError extends boolean = false>(options: Options<UsersControllerCreateUserData, ThrowOnError>) => (options.client ?? client).post<UsersControllerCreateUserResponses, unknown, ThrowOnError>({
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const usersControllerRemoveUser = <ThrowOnError extends boolean = false>(options: Options<UsersControllerRemoveUserData, ThrowOnError>) => (options.client ?? client).delete<UsersControllerRemoveUserResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const usersControllerGetUserById = <ThrowOnError extends boolean = false>(options: Options<UsersControllerGetUserByIdData, ThrowOnError>) => (options.client ?? client).get<UsersControllerGetUserByIdResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const usersControllerUpdateUser = <ThrowOnError extends boolean = false>(options: Options<UsersControllerUpdateUserData, ThrowOnError>) => (options.client ?? client).patch<UsersControllerUpdateUserResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });
