// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type RegisterDto = {
    name?: string;
    email: string;
    password: string;
};

export type LoginDto = {
    email: string;
    password: string;
};

export type AuthControllerGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type AuthControllerGetMeResponses = {
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type AuthControllerRegisterResponses = {
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginResponses = {
    200: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: unknown;
};

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type AuthControllerRefreshResponses = {
    200: unknown;
};

export type UsersControllerGetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type UsersControllerGetAllUsersResponses = {
    200: unknown;
};

export type UsersControllerCreateUserData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type UsersControllerCreateUserResponses = {
    201: unknown;
};

export type UsersControllerRemoveUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersControllerRemoveUserResponses = {
    204: void;
};

export type UsersControllerRemoveUserResponse = UsersControllerRemoveUserResponses[keyof UsersControllerRemoveUserResponses];

export type UsersControllerGetUserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersControllerGetUserByIdResponses = {
    200: unknown;
};

export type UsersControllerUpdateUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersControllerUpdateUserResponses = {
    200: unknown;
};
